accounts/urls.py
from .import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name='accounts'
urlpatterns=[
     path('login/',auth_views.LoginView.as_view(template_name="login.html"),name='login'),
    path('signup',views.SignUp.as_view(),name='signup'),
     path('logout/',auth_views.LogoutView.as_view(),name="logout"),
     
     
     
     
] 

recommendation_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from accounts import views
from accounts.views import image_detailview

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls')),
     #path('user_page/',views.user_loginpage,name='user_page'),
    path('thanks/',views.thankspage.as_view(),name='thanks'),
    path('',views.Homepage,name='homepage'),
   path('movie/<int:pk>/', views.image_detailview.as_view(),name='detail'),
  path('<int:pk>/',views.add_movie,name="movie_add"),
    path('list/',views.my_list,name='my_list'),
    path('searchresults/',views.search_results,name='search'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


#class User(auth.models.User,auth.models.PermissionsMixin):

#    def __str__(self):
 #       return (self.username)






class movie(models.Model):
    index=models.IntegerField(primary_key=True)
    movie_id=models.IntegerField()
    title=models.CharField(max_length=120)
    genres=models.CharField(max_length=130)
    imdb_id=models.IntegerField()
    tmdb_id=models.IntegerField()
    Image_url=models.URLField(max_length=200)
    text=models.TextField(max_length=400)

    def __str__(self):
        return self.title

class fav(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    movie=models.ForeignKey(movie, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):

    class Meta:
        fields=('username','email','password1','password2')
        model=get_user_model()

accounts/views.py
    
from django.shortcuts import render,get_object_or_404,HttpResponseRedirect,redirect
from django.views.generic import TemplateView,CreateView,DetailView,View
from django.urls import reverse_lazy,reverse
from . import forms
from django.contrib import messages
from django.contrib.auth import views as auth_views
from .models import movie,fav
from django.contrib.auth.models import User
from django.core.paginator import Paginator
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import sqlite3

class SignUp(CreateView):
    form_class=forms.UserCreateForm
    success_url=reverse_lazy('accounts:login')
    template_name='signup.html'


def add_movie(request,pk):
    
    # if fav.objects.filter(movie=pk,user=request.user.pk).exists():
    #    fav.objects.filter(movie=pk,user=request.user.pk).delete()
    # else:
        
    #     print(request.user.id)
    #     user=User.objects.filter(id=request.user.id)
    #     print(user)
    #     fav(movie=pk,user=user).save()
    
    # return HttpResponseRedirect('accounts/movie_detail.html')
    if fav.objects.filter(movie=pk,user=request.user.pk).exists():
        fav.objects.filter(movie=pk,user=request.user.pk).delete()
        messages.success(request, 'Removed from list.')
    else:
        
        print(request.user.id)
        movie_obj = movie.objects.filter(index=pk).first()
        user=User.objects.filter(id=request.user.id).first()
        print(user)
        fav_obj = fav(movie=movie_obj,user=user)
        messages.success(request, 'Added to list.')
        fav_obj.save()
    return redirect('detail',pk)


def search_results(request):
    if request.method=='POST':
        searched=request.POST['searched']
        movies_obj=movie.objects.filter(title__contains=searched)
        return render(request, 'search.html',{'movies_obj':movies_obj})
    else:
        
        return render(request, 'search.html',{})





def my_list(request):
    
    temp=fav.objects.filter(user__id=request.user.id)
    
    return render(request, 'my_list.html',{'temp':temp})


def Homepage(request):
   # movies_list=movie.objects.all()
    #return render(request, 'index.html',{'movies_list':movies_list})
    posts = movie.objects.all()  # fetching all post objects from database
    p = Paginator(posts, 18)  # creating a paginator object
    # getting the desired page number from url
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
    context = {'page_obj': page_obj,'posts':posts}
    # sending the page object to index.html
    return render(request, 'index.html', context)


class thankspage(TemplateView):
    template_name='logout.html'


class image_detailview(View):

    movie = movie
    def get(self, request, pk):
        movies_detail = self.movie.objects.get(pk=pk)
        print(movies_detail)

        # Create your connection.
        cnx = sqlite3.connect('db.sqlite3')

        df = pd.read_sql_query("SELECT * FROM accounts_movie", cnx)
        #print(df.head())
        features = ['genres', 'title','text']
        for f in features:
            df[f] = df[f].fillna('')

        
        def combineFeatures(row):
            return row['genres'] + " " + row['title']+" "+row['text']

        df['combineFeatures'] = df.apply(combineFeatures, axis = 1)
        print(df['combineFeatures'])
        cv = CountVectorizer()
        count_matrix = cv.fit_transform(df['combineFeatures'])
        cosine_sim = cosine_similarity(count_matrix)
        

        movie_obj = self.movie.objects.filter(index=pk).first()
        movie_user_likes=movie_obj.title
        print(movie_user_likes)
    
    

        def get_index_from_title(title):
            return df[df.title == title]["index"].values[0]

        movie_index = get_index_from_title(movie_user_likes)
        print(movie_index)

        similar_movies = list(enumerate(cosine_sim[movie_index]))
        sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

        def get_title_from_index(index):
            return df[df.index == index]["index"].values[0]
        i=0
        li=[]
        for x in sorted_similar_movies:
            get_index = get_title_from_index(x[0])
            
            recommendation_list_obj=movie.objects.get(index=get_index)
            
            li.append(recommendation_list_obj)


            print(get_title_from_index(x[0]))
            i=i+1
            if i>17:
                break
        print(li)
        return render(request,'accounts/movie_detail.html',{'li':li,'movie':movies_detail})





#class HomePage(TemplateView):
#    template_name='index.html'

templates/accounts/movie_detail.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <div class="alert alert-success">
              <strong>Success!</strong> {{message}}
            </div>
        {% endfor %}
    </ul>
{% endif %}
<div class="row" class="d-flex justify-content-center">
    
    <div class="col-sm-2 col-md-2">
      <div class="thumbnail">
      <div class="card">
        
          <img src="{{movie.Image_url}}"  style="width:100%" alt="Card image" class="rounded">
      

          <div class="card-title text-center">
            {{movie.title}}
          </div>
          <div class="text-info">
          <p class="card-text text-center" > {{movie.genres}}

          </p>
        </div>
           
          
        </div>
      
      </div>
    </div>
    <div>
   <a href="{% url 'movie_add' movie.pk %}" class="btn btn-outline-primary">Add to my list</button>
    </a>
    
  </div>
  
   
  
    </div>
    <br>
    <h6>About:
      <p>
        {{movie.text}}
      </p>
      </h6>

<br>
<br>
    <div class="container-fluid">
      <h2>Recommendations for you</h2>
    </div>
    <hr>
    <br>
    
    <div class="row">
      {%if li%}
      {%for x in li%}
      <div class="col-sm-2 col-md-2">
        <div class="thumbnail">
        <div class="card">
         
            <img src="{{x.Image_url}}"  style="width:100%" alt="Card image" class="rounded">
         
  
            <div class="card-title text-center">
              {{x.title}}
            </div>
            <div class="text-info">
              <p class="card-text text-center" > {{movie.genres}}
    
              </p>
            </div>
          </div>
        
        </div>
      </div>
        {%endfor%}
      </div>
  {%endif%}
    {%else%}
  <h1>login Required </h1>

  {%endif%}
{%endblock%}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recommendation system</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
  
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid"> 
 <!--   <nav class="navbar mynav"  role="navigation" id='navbar'>-->

       
            <a class='navbar-brand' href="{%url 'homepage'%}">Recommendation system</a>

<ul class="nav navbar-nav navbar-right">

    {%if user.is_authenticated%}
 
 <li ><a href="{%url 'accounts:logout'%}" class="nav-item nav-link px-3">logout</a></li>
 <li><a href="{%url 'my_list'%}" class="nav-item nav-link px-3">My list</a></li>
 

 {%else%}


    <li><a href="{%url 'accounts:signup'%}" class="nav-item nav-link px-3"> Sign Up</a></li>
    
    <li><a href="{%url 'accounts:login'%}" class="nav-item nav-link px-3"> Login</a></li>
  </ul>
  <!--
 <li><a href="{%url 'accounts:login'%}">login</a></li>
 <li><a href="{%url 'accounts:signup'%}">signup</a></li>
 -->
 {%endif%}


</div>
</nav>
  <div>
      <br>
<br>      <center>

    {%if user.is_authenticated%}
        welcome {{user.username}}
      </center>
      {%endif%}
  </div>

 <br>
 <br>
      <form action="{%url 'search'%}" method="POST">
          {%csrf_token%}
          <center>
            
  <input type="search" class="form-control mb-2 mr-sm-2" placeholder="search" id="search" name="searched">
  <button type="submit" class="btn btn-primary mb-2">Search</button>
        </center>
      </form>
  
   
   <br>
   <br>
    

    <div class="container">
        {%block content%}

        {%endblock%}
    </div>
    
</body>
</html>

templates/index.html
{%extends "base.html"%}
{%block content%}
 
      <div class="row">
      {% for x in page_obj.object_list %}
      
      <div class="col-sm-2 col-md-2">
        <div class="thumbnail">
        <div class="card">
          
          <a href="{% url 'detail' x.pk %}">
            <img src="{{x.Image_url}}"  style="width:100%" alt="Card image" class="rounded">
          </a>
  
            <div class="card-title text-center">
              {{x.title}}
            </div>
          </div>
        
        </div>
      </div>
      
       {% endfor %}
  </div>
  <div class="container p-3 my-3 bg-dark text-white">
  <div class="d-flex justify-content-center" >
  <div class="pagination" >
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            
            <a href="?page={{ page_obj.previous_page_number }}"><button class="btn btn-primary" class="bi bi-arrow-left-square-fill">Previous</button>

            </a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"><button  class="btn btn-primary" class="bi bi-arrow-right-square-fill">Next</button></a>
            
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
</div>
{%endblock%}



                   
 

templates/login.html
{%extends 'base.html'%}
{%load bootstrap4%}
{%block content%}

<div class="container">
<h1>sign in!</h1>
<form method="POST">
{%csrf_token%}

{%bootstrap_form form%}

<input type="submit" class="btn btn-default" value="login">

</form>


</div>

{%endblock%}

templates/logout.html
{%extends 'base.html'%}

{%block content%}
<h1>thnks for visiting</h1>
{%endblock%}

templates/my_list.html
{%extends "base.html"%}
{%block content%}
<div class="row">
    {%if temp%}
    {%for x in temp%}
    <div class="col-sm-2 col-md-2">
      <div class="thumbnail">
      <div class="card">
       
          <img src="{{x.movie.Image_url}}"  style="width:100%" alt="Card image" class="rounded">
       

          <div class="card-title text-center">
            {{x.title}}
          </div>
        </div>
      
      </div>
    </div>
      {%endfor%}
    </div>
    
    {% else %}
        <div class="alert alert-danger">
            <strong>Sorry!</strong> No movies in your list.
        </div>
    {% endif %}
{%endblock%}

templates/search.html
{% extends "base.html" %}
{% block content %}
{%if movies_obj%}
<div class="row" >
{%for x in movies_obj%}

  
  <div class="col-sm-2 col-md-2">
    <div class="thumbnail">
    <div class="card">
     <a href="{%url 'detail' x.pk%}">
        <img src="{{x.Image_url}}"  style="width:100%" alt="Card image" class="rounded">
      </a>

        <div class="card-title text-center">
          {{x.title}}
        </div>
      </div>
    
    </div>
  </div>
    

  
  {%endfor%}
</div>
{%else%}
<h3>You forgot for search</h3>
{%endif%}
{%endblock%}

templates/signup.html
{%extends 'base.html'%}
{%load bootstrap4%}
{%block content%}

<div class="container">
<h1>sign up!</h1>
<form method="POST">
{%csrf_token%}

{%bootstrap_form form%}

<input type="submit" class="btn btn-default" value="sign up">

</form>


</div>

{%endblock%}

templates/user_page.html
{%extends 'base.html'%}

{%block content%}
<h1>u r now logged in</h1>
{%endblock%}